apiVersion: v1
kind: Pod
metadata:
  name: hello-static
  namespace: default
spec:
  hostNetwork: false
  restartPolicy: Always
  securityContext:
    seccompProfile:
      type: Unconfined
  containers:
  - name: hello
    image: docker.io/library/hello:latest
    command: ["/bin/sleep", "300"]
    imagePullPolicy: Never
    securityContext:
      seccompProfile:
        type: Unconfined
