// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: registration/registration.proto

package registration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_registration_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{0}
}

type PluginInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint          string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SupportedVersions []string               `protobuf:"bytes,4,rep,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_registration_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PluginInfo) GetSupportedVersions() []string {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

type RegistrationStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PluginRegistered bool                   `protobuf:"varint,1,opt,name=plugin_registered,json=pluginRegistered,proto3" json:"plugin_registered,omitempty"`
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegistrationStatus) Reset() {
	*x = RegistrationStatus{}
	mi := &file_registration_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationStatus) ProtoMessage() {}

func (x *RegistrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationStatus.ProtoReflect.Descriptor instead.
func (*RegistrationStatus) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationStatus) GetPluginRegistered() bool {
	if x != nil {
		return x.PluginRegistered
	}
	return false
}

func (x *RegistrationStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegistrationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationStatusResponse) Reset() {
	*x = RegistrationStatusResponse{}
	mi := &file_registration_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationStatusResponse) ProtoMessage() {}

func (x *RegistrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationStatusResponse.ProtoReflect.Descriptor instead.
func (*RegistrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{3}
}

var File_registration_registration_proto protoreflect.FileDescriptor

const file_registration_registration_proto_rawDesc = "" +
	"\n" +
	"\x1fregistration/registration.proto\x12\x12pluginregistration\"\r\n" +
	"\vInfoRequest\"\x7f\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12-\n" +
	"\x12supported_versions\x18\x04 \x03(\tR\x11supportedVersions\"W\n" +
	"\x12RegistrationStatus\x12+\n" +
	"\x11plugin_registered\x18\x01 \x01(\bR\x10pluginRegistered\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1c\n" +
	"\x1aRegistrationStatusResponse2\xd2\x01\n" +
	"\fRegistration\x12L\n" +
	"\aGetInfo\x12\x1f.pluginregistration.InfoRequest\x1a\x1e.pluginregistration.PluginInfo\"\x00\x12t\n" +
	"\x18NotifyRegistrationStatus\x12&.pluginregistration.RegistrationStatus\x1a..pluginregistration.RegistrationStatusResponse\"\x00B\x17Z\x15test-csi/registrationb\x06proto3"

var (
	file_registration_registration_proto_rawDescOnce sync.Once
	file_registration_registration_proto_rawDescData []byte
)

func file_registration_registration_proto_rawDescGZIP() []byte {
	file_registration_registration_proto_rawDescOnce.Do(func() {
		file_registration_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registration_registration_proto_rawDesc), len(file_registration_registration_proto_rawDesc)))
	})
	return file_registration_registration_proto_rawDescData
}

var file_registration_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_registration_registration_proto_goTypes = []any{
	(*InfoRequest)(nil),                // 0: pluginregistration.InfoRequest
	(*PluginInfo)(nil),                 // 1: pluginregistration.PluginInfo
	(*RegistrationStatus)(nil),         // 2: pluginregistration.RegistrationStatus
	(*RegistrationStatusResponse)(nil), // 3: pluginregistration.RegistrationStatusResponse
}
var file_registration_registration_proto_depIdxs = []int32{
	0, // 0: pluginregistration.Registration.GetInfo:input_type -> pluginregistration.InfoRequest
	2, // 1: pluginregistration.Registration.NotifyRegistrationStatus:input_type -> pluginregistration.RegistrationStatus
	1, // 2: pluginregistration.Registration.GetInfo:output_type -> pluginregistration.PluginInfo
	3, // 3: pluginregistration.Registration.NotifyRegistrationStatus:output_type -> pluginregistration.RegistrationStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_registration_registration_proto_init() }
func file_registration_registration_proto_init() {
	if File_registration_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registration_registration_proto_rawDesc), len(file_registration_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registration_registration_proto_goTypes,
		DependencyIndexes: file_registration_registration_proto_depIdxs,
		MessageInfos:      file_registration_registration_proto_msgTypes,
	}.Build()
	File_registration_registration_proto = out.File
	file_registration_registration_proto_goTypes = nil
	file_registration_registration_proto_depIdxs = nil
}
