#include <linux/export-internal.h>

#include <linux/module.h>
#undef __MODULE_INFO_PREFIX
#define __MODULE_INFO_PREFIX
MODULE_INFO(irq_gic_v5_iwb.alias, "of:N*T*Carm,gic-v5-iwb");
MODULE_INFO(irq_gic_v5_iwb.alias, "of:N*T*Carm,gic-v5-iwbC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Csimple-pm-bus");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Csimple-pm-busC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Csimple-bus");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Csimple-busC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Csimple-mfd");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Csimple-mfdC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cisa");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*CisaC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Carm,amba-bus");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Carm,amba-busC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1021a-scfg");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1021a-scfgC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1043a-scfg");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1043a-scfgC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1046a-scfg");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1046a-scfgC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1088a-isc");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls1088a-iscC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls2080a-isc");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,ls2080a-iscC*");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,lx2160a-isc");
MODULE_INFO(simple_pm_bus.alias, "of:N*T*Cfsl,lx2160a-iscC*");
MODULE_INFO(clk_fixed_factor.alias, "of:N*T*Cfixed-factor-clock");
MODULE_INFO(clk_fixed_factor.alias, "of:N*T*Cfixed-factor-clockC*");
